/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.sam;

import co.sam.livecheck.LiveCheckerClient;

public class App {

    public static void main(String[] args) throws Exception {

        String serverEndpoint = System.getenv().getOrDefault("GRPC_SERVER", "java-grpc-server");
        int serverPort = Integer.parseInt(System.getenv().getOrDefault("GRPC_PORT", "0"));
        String apiKey = "AIzaSyC0LcIf0WJMpbCy9nVpqKZ9RAl8LaK1zJQ";

        LiveCheckerClient client = new LiveCheckerClient(serverEndpoint, serverPort, apiKey);

        try {

            String message = client.checkService();
            System.out.println("message:" + message);

        } finally {
            client.shutdown();
        }

    }
}
