/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.sam;

import co.sam.livecheck.LiveCheckerClient;

public class App {

    public static void main(String[] args) throws Exception {

        LiveCheckerClient client = new LiveCheckerClient("localhost", 50051);

        try{

            String message = client.checkService();
            System.out.println("message:" + message);

        }finally {
            client.shutdown();
        }

    }
}
